services:
  nginx:
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - generated_images:/data/images:ro
      - ./content:/data/content:ro
      - /var/www/certbot:/var/www/certbot:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - frontend_dist:/usr/share/nginx/html:ro

  bot:
    environment:
      IS_PROD: "true"
