"""empty message

Revision ID: 00aaa1c22734
Revises: 1eefaea35b12
Create Date: 2026-01-27 20:55:48.713919

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '00aaa1c22734'
down_revision: Union[str, None] = '1eefaea35b12'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('characters', sa.Column('created_by_username_id', sa.BigInteger(), nullable=True))
    op.add_column('characters', sa.Column('created_by_username', sa.String(length=255), nullable=True))
    op.create_foreign_key(None, 'characters', 'users', ['created_by_username_id'], ['telegram_id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'characters', type_='foreignkey')
    op.drop_column('characters', 'created_by_username')
    op.drop_column('characters', 'created_by_username_id')
    # ### end Alembic commands ###
