"""empty message

Revision ID: 0647d50443af
Revises: c451dcfc772d
Create Date: 2026-01-26 13:45:06.156753

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0647d50443af'
down_revision: Union[str, None] = 'c451dcfc772d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chats', sa.Column('last_auto_photo_at', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chats', 'last_auto_photo_at')
    # ### end Alembic commands ###
