"""empty message

Revision ID: 1eefaea35b12
Revises: 0647d50443af
Create Date: 2026-01-28 09:05:37.349411

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1eefaea35b12'
down_revision: Union[str, None] = '0647d50443af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prompts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prompts_category'), 'prompts', ['category'], unique=False)
    op.create_index(op.f('ix_prompts_key'), 'prompts', ['key'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_prompts_key'), table_name='prompts')
    op.drop_index(op.f('ix_prompts_category'), table_name='prompts')
    op.drop_table('prompts')
    # ### end Alembic commands ###
