"""add cover_image to worlds

Revision ID: 946b1afaa646
Revises: 3f18c6807b1c
Create Date: 2026-01-21 09:08:21.554395

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '946b1afaa646'
down_revision: Union[str, None] = '3f18c6807b1c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('worlds', sa.Column('cover_image', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('worlds', 'cover_image')
    # ### end Alembic commands ###
