"""empty message

Revision ID: ae460fad6849
Revises: b4cef5d5921d
Create Date: 2026-02-05 13:14:07.176523

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae460fad6849'
down_revision: Union[str, None] = 'b4cef5d5921d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('characters', sa.Column('is_public', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('characters', 'is_public')
    # ### end Alembic commands ###
