"""add_nsfw_level_to_generated_images

Revision ID: b4cef5d5921d
Revises: 00aaa1c22734
Create Date: 2026-01-30 12:55:35.022127

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b4cef5d5921d'
down_revision: Union[str, None] = '00aaa1c22734'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('generated_images', sa.Column('nsfw_level', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('generated_images', 'nsfw_level')
    # ### end Alembic commands ###
