"""empty message

Revision ID: c451dcfc772d
Revises: a1b2c3d4e5f6
Create Date: 2026-01-25 20:41:25.165541

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c451dcfc772d'
down_revision: Union[str, None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('is_auto_generated', sa.Boolean(), nullable=True))
    op.execute("UPDATE messages SET is_auto_generated = FALSE WHERE is_auto_generated IS NULL")
    op.alter_column('messages', 'is_auto_generated', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'is_auto_generated')
    # ### end Alembic commands ###
