import os
from pathlib import Path

BOT_TOKEN = os.getenv("BOT_TOKEN")

CONTENT_BASE_PATH = Path(os.getenv("CONTENT_PATH", "/app/content"))

DATABASE_URL = os.getenv("DATABASE_URL")
if DATABASE_URL.startswith("postgresql://"):
    DATABASE_URL = DATABASE_URL.replace("postgresql://", "postgresql+asyncpg://")

OPENROUTER_API_KEY = os.getenv("OPENROUTER_API_KEY")
OPENROUTER_BASE_URL = "https://openrouter.ai/api/v1/chat/completions"
OPENROUTER_IDENTITY_MODEL = os.getenv("OPENROUTER_IDENTITY_MODEL", "google/gemini-2.5-flash")
OPENROUTER_IDENTITY_TIMEOUT_SECONDS = int(os.getenv("OPENROUTER_IDENTITY_TIMEOUT_SECONDS", "60"))

LLM_ACTIVE_MODEL_PROMPT_KEY = "llm_active_model"
CHAT_MODEL = os.getenv("CHAT_MODEL", "deepseek/deepseek-v4-flash")
STRUCTURED_MODEL = os.getenv("STRUCTURED_MODEL", "qwen/qwen3.6-flash")
SUMMARY_MODEL = os.getenv("SUMMARY_MODEL", CHAT_MODEL)
PLAYER_MODEL = os.getenv("PLAYER_MODEL", CHAT_MODEL)

LLM_MODEL_CHOICES = {
    "deepseek_v4_flash": {
        "label": "DeepSeek V4 Flash",
        "model": "deepseek/deepseek-v4-flash",
    },
    "qwen3_6_flash": {
        "label": "Qwen3.6 Flash (Structured)",
        "model": "qwen/qwen3.6-flash",
    },
}
LLM_DEFAULT_PROVIDER = os.getenv("LLM_DEFAULT_PROVIDER", "deepseek_v4_flash")
LLM_DEFAULT_ACTIVE_MODEL = LLM_MODEL_CHOICES.get(
    LLM_DEFAULT_PROVIDER,
    LLM_MODEL_CHOICES["deepseek_v4_flash"],
)["model"]
LLM_MODEL = os.getenv("LLM_MODEL", CHAT_MODEL)

LLM_MAX_TOKENS_CHARACTER = 1200
LLM_MAX_TOKENS_WORLD = 1200
LLM_TEMPERATURE = float(os.getenv("LLM_TEMPERATURE", "0.35"))
LLM_TOP_P = float(os.getenv("LLM_TOP_P", "0.9"))
LLM_REPETITION_PENALTY = float(os.getenv("LLM_REPETITION_PENALTY", "1.15"))

SUMMARY_THRESHOLD = 15
MAX_HISTORY_LENGTH = 10


SCENE_ANALYZER_ENABLED = os.getenv("SCENE_ANALYZER_ENABLED", "true").lower() == "true"
SCENE_ANALYZER_MODEL = os.getenv("SCENE_ANALYZER_MODEL", STRUCTURED_MODEL)
SCENE_ANALYZER_TIMEOUT = int(os.getenv("SCENE_ANALYZER_TIMEOUT", "10"))

IMAGES_STORAGE_PATH = os.getenv("IMAGES_STORAGE_PATH", "/app/generated_images")
IMAGES_BASE_URL = os.getenv("IMAGES_BASE_URL", "http://localhost/images")  
ADMIN_TELEGRAM_IDS = [int(x) for x in os.getenv("ADMIN_TELEGRAM_IDS", "").split(",") if x.strip()]

RUNPOD_API_KEY = os.getenv("RUNPOD_API_KEY") or os.getenv("RUNPOD_KEY")
RUNPOD_MANHWA_ENDPOINT_ID = os.getenv("RUNPOD_MANHWA_ENDPOINT_ID")
RUNPOD_MANHWA_TIMEOUT_SECONDS = int(os.getenv("RUNPOD_MANHWA_TIMEOUT_SECONDS", "900"))
RUNPOD_MANHWA_POLL_INTERVAL_SECONDS = int(os.getenv("RUNPOD_MANHWA_POLL_INTERVAL_SECONDS", "3"))
RUNPOD_FACEFUSION_ENDPOINT_ID = os.getenv("RUNPOD_FACEFUSION_ENDPOINT_ID", "nif211wfdmdmc5")
RUNPOD_FACEFUSION_TIMEOUT_SECONDS = int(os.getenv("RUNPOD_FACEFUSION_TIMEOUT_SECONDS", "1200"))
RUNPOD_FACEFUSION_POLL_INTERVAL_SECONDS = float(os.getenv("RUNPOD_FACEFUSION_POLL_INTERVAL_SECONDS", "3"))
RUNPOD_FACEFUSION_PRESET = os.getenv("RUNPOD_FACEFUSION_PRESET", "hyperswap_1a_512")
RUNPOD_FACEFUSION_OUTPUT_FORMAT = os.getenv("RUNPOD_FACEFUSION_OUTPUT_FORMAT", "png")
RUNPOD_FACEFUSION_EXECUTION_TIMEOUT_MS = int(
    os.getenv("RUNPOD_FACEFUSION_EXECUTION_TIMEOUT_MS", str(RUNPOD_FACEFUSION_TIMEOUT_SECONDS * 1000))
)
RUNPOD_FACEFUSION_TTL_MS = int(
    os.getenv(
        "RUNPOD_FACEFUSION_TTL_MS",
        str(max(RUNPOD_FACEFUSION_EXECUTION_TIMEOUT_MS + 900_000, 3_600_000)),
    )
)

REPLICATE_API_TOKEN = os.getenv("REPLICATE_API_TOKEN")
REPLICATE_REAL_MODEL = os.getenv(
    "REPLICATE_REAL_MODEL",
    "prunaai/z-image-turbo",
)
REPLICATE_REAL_WIDTH = int(os.getenv("REPLICATE_REAL_WIDTH", "1024"))
REPLICATE_REAL_HEIGHT = int(os.getenv("REPLICATE_REAL_HEIGHT", "1024"))
REPLICATE_REAL_NUM_INFERENCE_STEPS = int(os.getenv("REPLICATE_REAL_NUM_INFERENCE_STEPS", "9"))
REPLICATE_REAL_GUIDANCE_SCALE = float(os.getenv("REPLICATE_REAL_GUIDANCE_SCALE", "0.0"))
REPLICATE_REAL_NUM_OUTPUTS = int(os.getenv("REPLICATE_REAL_NUM_OUTPUTS", "1"))
REPLICATE_REAL_SCHEDULER = os.getenv("REPLICATE_REAL_SCHEDULER", "K_EULER")
REPLICATE_REAL_DISABLE_SAFETY_CHECKER = (
    os.getenv("REPLICATE_REAL_DISABLE_SAFETY_CHECKER", "true").lower() == "true"
)
REPLICATE_REAL_TIMEOUT_SECONDS = int(os.getenv("REPLICATE_REAL_TIMEOUT_SECONDS", "180"))
REPLICATE_REAL_POLL_INTERVAL_SECONDS = float(os.getenv("REPLICATE_REAL_POLL_INTERVAL_SECONDS", "2"))
